### PR TITLE
v0.3 Fourier

### LINKED ISSUE #253: Julia fourier example update for v0.3
Based on the new syntax of v0.3 we need to update the example on drawing the Julia logo using fourier.

### PR DESCRIPTION
**Pull request by Wikunia**
## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [ ] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [ ] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [ ] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [ ] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [ ] Did I properly add test dependencies to the `test` directory (if applicable)?
- [ ] Did I check relevant tutorials that may be affected by changes in this PR?
- [ ] Did I clearly articulate why this PR was made the way it was and how it was made?

**Link to relevant issue(s)**
Closes #253 

**How did you address these issues with this PR? What methods did you use?**
I've wrote the example from scratch to use v0.3 syntax.

With this I used the `julialogo` function as well as `TravelingSalesmanHeuristics` .
One major change compared to before is that I integrate the vector into the circle such that they are connected and one only needs to rotate the circle without the need to draw the vector in it afterwards by using the point. I found it easier to return the tip of the vector from the circ function than the center to make everything smooth.

A result can be seen here: https://youtu.be/rrmx2Q3sO1Y

I've mentioned @ric-cioffi at the top of the file as inspiration. Feel free to have a look at the code to see how one can achieve it in v0.3 @ric-cioffi . Things that I left out atm are: fadein and fadeout 

If everyone is happy with this I would probably remove the script by @ric-cioffi from the examples folder and the csv and would put a link to the v0.2 version using the git hash to the old version.

The .gif should be updated with the new version. Do you mind sending me the dimensions you would like to have in the showcases @TheCedarPrince ?

### CODE REVIEW

**Comment by TheCedarPrince** [comment]
@Wikunia the dimensions are 350 x 219 px for the gif!

**Review by TheCedarPrince — CHANGES_REQUESTED** [review]
Hunh, I am getting this strange error when I try to run the code:

```julia
ERROR: LoadError: There is no current drawing.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] get_current_cr() at /home/cedarprince/.julia/packages/Luxor/Sjhki/src/drawings.jl:53
 [3] translate at /home/cedarprince/.julia/packages/Luxor/Sjhki/src/basics.jl:542 [inlined]
 [4] translate at /home/cedarprince/.julia/packages/Luxor/Sjhki/src/basics.jl:543 [inlined]
 [5] julialogo(; action::Symbol, color::Bool, bodycolor::ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}}, centered::Bool) at /home/cedarprince/.julia/packages/Luxor/Sjhki/src/juliagraphics.jl:66
 [6] get_points(::Int64, ::NamedTuple{(:npoints, :nplay_frames, :nruns, :nend_frames, :width, :height, :shape_scale, :filename),Tuple{Int64,Int64,Int64,Int64,Int64,Int64,Float64,String}}) at /home/src/Projects/javis/examples/fourier.jl:57
 [7] animate_fourier(::NamedTuple{(:npoints, :nplay_frames, :nruns, :nend_frames, :width, :height, :shape_scale, :filename),Tuple{Int64,Int64,Int64,Int64,Int64,Int64,Float64,String}}) at /home/src/Projects/javis/examples/fourier.jl:114
 [8] main() at /home/src/Projects/javis/examples/fourier.jl:179
 [9] top-level scope at /home/src/Projects/javis/examples/fourier.jl:182
 [10] include(::String) at ./client.jl:457
 [11] top-level scope at REPL[1]:1
in expression starting at /home/src/Projects/javis/examples/fourier.jl:182
caused by [exception 1]
BoundsError: attempt to access 0-element Array{Drawing,1} at index [1]
Stacktrace:
 [1] getindex at ./array.jl:809 [inlined]
 [2] get_current_cr() at /home/cedarprince/.julia/packages/Luxor/Sjhki/src/drawings.jl:51
 [3] translate at /home/cedarprince/.julia/packages/Luxor/Sjhki/src/basics.jl:542 [inlined]
 [4] translate at /home/cedarprince/.julia/packages/Luxor/Sjhki/src/basics.jl:543 [inlined]
 [5] julialogo(; action::Symbol, color::Bool, bodycolor::ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}}, centered::Bool) at /home/cedarprince/.julia/packages/Luxor/Sjhki/src/juliagraphics.jl:66
 [6] get_points(::Int64, ::NamedTuple{(:npoints, :nplay_frames, :nruns, :nend_frames, :width, :height, :shape_scale, :filename),Tuple{Int64,Int64,Int64,Int64,Int64,Int64,Float64,String}}) at /home/src/Projects/javis/examples/fourier.jl:57
 [7] animate_fourier(::NamedTuple{(:npoints, :nplay_frames, :nruns, :nend_frames, :width, :height, :shape_scale, :filename),Tuple{Int64,Int64,Int64,Int64,Int64,Int64,Float64,String}}) at /home/src/Projects/javis/examples/fourier.jl:114
 [8] main() at /home/src/Projects/javis/examples/fourier.jl:179
 [9] top-level scope at /home/src/Projects/javis/examples/fourier.jl:182
 [10] include(::String) at ./client.jl:457
 [11] top-level scope at REPL[1]:1
```

Perhaps there was something defined in your REPL that is causing this to fail? I ran this without having Revise or any other package installed and used the latest version of Javis from this branch. 

Otherwise, this looks FREAKING AWESOME!!! Great work!

**Comment by Wikunia** [comment]
Oh one needs to define a `Drawing` for julialogo. Will fix

**Comment by Wikunia** [comment]
Fixed

**Comment by TheCedarPrince** [comment]
@Wikunia - looks good to me! Only question left is if it is supposed to be red? 

image

Can you replace the gif in the `/examples/gifs/` directory with the dimensions I asked for?

**Comment by Wikunia** [comment]
Yeah I've set the color to red so it's supposed to be red :joy:

**Comment by TheCedarPrince** [comment]
Haha, got it! It looked a little spooky was all. :ghost: Anyhow, feel free to merge!

**Review by TheCedarPrince — APPROVED** [review]

**Comment by ric-cioffi** [comment]
Looks great, nice job. Just one, very minor, "aesthetic" comment: with all the circles towards the final tip you only see a white blob moving around. I think it'd look nicer with a lower transparency/linewidth. In particular, IIRC, I had a fairly low transparency on the circles while left it high on the vectors.

Other than that it looks awesome :+1:

**Comment by Wikunia** [comment]
Ah I see. Thanks for your comment @ric-cioffi 
I played around with vectors a bit and the tip of it without thinking about the circles 😂

**Pull request merged**
