### PR TITLE
Add chaos game example

### PR DESCRIPTION
**Pull request by razetime**
## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [x] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [x] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [x] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [x] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [x] Did I properly add test dependencies to the `test` directory (if applicable)?
- [x] Did I check relevant tutorials that may be affected by changes in this PR?
- [x] Did I clearly articulate why this PR was made the way it was and how it was made?

**Link to relevant issue(s)**
Relating to #377

### CODE REVIEW

**Comment by gpucce** [comment]
Hi @razetime don't know if it is in the making but you could add the `chaosgame.gif` to docs/src/assets/ and then modify docs/src/examples.md so it shows in documentstion!

**Comment by razetime** [comment]
Sure, I will add the gif.

**Comment by gpucce** [comment]
I think you have a [Follow Path] that is a typo :)

**Comment by Wikunia** [comment]
Thanks a lot @razetime sorry for the late merge

**Pull request merged**
