### PR TITLE
Draw latex

### LINKED ISSUE #170: Make LaTeX Appear/Disappear
**Is your feature request related to a problem? Please explain.**

Currently only text can `appear` or `disappear`. It would be great to implement a similar idea for `LaTeX` strings.

### PR DESCRIPTION
**Pull request by Wikunia**
## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [x] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [x] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [x] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [x] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [x] Did I properly add test dependencies to the `test` directory (if applicable)?
- [x] Did I check relevant tutorials that may be affected by changes in this PR?
- [x] Did I clearly articulate why this PR was made the way it was and how it was made?

**Link to relevant issue(s)**
Closes #170 

**How did you address these issues with this PR? What methods did you use?**
I compute the width and height of the latex string and then use it as a clipping region and a circle grows from the top left corner to make it appear like the text is drawn from left to right. This is quite similar to what I have done for #161

### CODE REVIEW

**Review by TheCedarPrince — APPROVED** [review]
LGTM - everything makes sense. I only have two critiques that I can think of is maybe to update the HowTo with saying how to draw LaTeX. You could also open that up in another PR if you want. 

Else, I noticed when rendering a matrix, the appear and disappear somewhat "swoops" into the animation and over top the words being appeared and disappeared. I am not sure if we want something more regular like a square instead of a circle being dragged across the LaTeX. Here is an example of what I mean by the "swooping" behavior:

latex

Otherwise, I approve! Great work!

**Comment by Wikunia** [comment]
I think different settings make sense i.e `appear(:draw_text; type=:rect)` 
Do you mind to check my add to the how to section?

**Comment by Wikunia** [comment]
Is this good to go and we handle the rect thing later? @TheCedarPrince

**Comment by TheCedarPrince** [comment]
Hey @Wikunia - I agree, this is good to go and we can deal with the rect thing later. I will open a new PR on that right now as I already starting roughing out a possible solution. I'll go ahead and merge.

**Pull request merged**
