### PR TITLE
Example - Gravities of the Solar System

### LINKED ISSUE #360: Idea for a Javis example
https://twitter.com/physicsJ/status/1414233142861262855

This can make up for a good example for someone new to Javis as a contributor.

### PR DESCRIPTION
**Pull request by MisterBiggs**
## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [ ] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [x] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [x] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [x] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [x] Did I properly add test dependencies to the `test` directory (if applicable)?
- [x] Did I check relevant tutorials that may be affected by changes in this PR?
- [x] Did I clearly articulate why this PR was made the way it was and how it was made?

**Link to relevant issue(s)**
Closes #360

**How did you address these issues with this PR? What methods did you use?**

Not sure if you would like to bump the version in the `CHANGELOG.md` just for an example. 

Otherwise, the code in this PR is just for a new example. The example has been added to the repos [`/examples`](https://github.com/Wikunia/Javis.jl/tree/master/examples) folder as well as the [Examples](https://wikunia.github.io/Javis.jl/stable/examples/) in the docs. Below is an example of the finished animation!

test

### CODE REVIEW

**Review by Wikunia — COMMENTED** [review]
The animation looks awesome! Thanks for creating the PR. I think we should try to use `act!` to update the positions of each planet though instead of creating new objects every time. 
You can find some examples and explanations regarding that in my latest blog posts: https://opensourc.es 
Let us know when you have any questions.

**Review by Wikunia — COMMENTED** [review]
I'm not sure whether this was ready for review again ;) Please ping me next time you want another review. Thanks for rewriting it with actions. Let me know if you need any help or whether we can make some stuff more clear in tutorials and such.

**Comment by Sov-trotter** [comment]
Hey people. This PR Looks really solid!
>  However it might make sense to try it out without it first and learn the best approach of how to make it internal later on.

I can't agree more @Wikunia. Before having some rigid math/physics/any computational stuff it would be better to have multiple examples before hand. We could divide and exand the examples sections though(based on domain). Also I would love to see how we can possibly integrate other physics based/domain specific packages from the julia package ecosystem since those will be much more performant and also save us time.

**Review by Wikunia — APPROVED** [review]
Awesome thanks for this stunning work.

**Pull request merged**
