### PR TITLE
Postprocessing frame check bug fix 

### PR DESCRIPTION
**Pull request by gpucce**
## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [ ] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [ ] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [ ] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [ ] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [ ] Did I properly add test dependencies to the `test` directory (if applicable)?
- [ ] Did I check relevant tutorials that may be affected by changes in this PR?
- [ ] Did I clearly articulate why this PR was made the way it was and how it was made?

**Link to relevant issue(s)**
Closes #

**How did you address these issues with this PR? What methods did you use?**
The check for frames returned by `postprocess_frames_flow` was wrongly written, this should fix it.

### CODE REVIEW

**Comment by Wikunia** [comment]
I don't know how the previous code could result in a failure. Probably missing something here. Aren't the frames always from 1-... ? Isn't gif rendering would fail otherwise? Maybe add a test which would fail in the current version and is fixed by this.

Btw make sure to update your personal fork before creating a PR. (For the next one don't worry about this one) as currently this PR has >30 commits but only the last is the one which isn't merged already

**Comment by gpucce** [comment]
Sorry for merging I though I did. 

The error was this, I think for javis is not an issue having for example frame 0 defined but with the old solution this would throw this error instead of using frame 0 normally, now it shouldn't anymore.

**Comment by gpucce** [comment]
So I adapted a test in postprocessing to account for the negative frames and it does work with this PR while it does not without it.

**Comment by Wikunia** [comment]
Great thanks

**Review by Wikunia — COMMENTED** [review]
Thanks LGTM. Please add a line to the changelog :) 
Then I'll merge and tag a new release

**Comment by gpucce** [comment]
That should be it!

**Pull request merged**
