### PR TITLE
fix for AbstractPaths using conversion to string

### PR DESCRIPTION
**Pull request by Wikunia**
@jordancluts do you mind to test this on your machine?

Should be a fix for #116

### CODE REVIEW

**Comment by jordancluts** [comment]
Worked like a charm

```
julia> javis(
           myvideo,
           [
               BackgroundAction(1:70, ground),
               Action(1:70, :red_ball, (args...) -> object(Point(100,0), "red")),
           ],
           pathname=p"circle2.gif"
       )
"circle2.gif"
```

**Comment by Wikunia** [comment]
@jordancluts thanks for testing. Do you mind to test it with directories as well? So i.e `p"gifs/circle2.gif"` as I actually think your example should have worked before.

**Comment by jordancluts** [comment]
Of course, I blame morning brain. Including a folder also worked fine.

```
julia> javis(
           myvideo,
           [
               BackgroundAction(1:70, ground),
               Action(1:70, :red_ball, (args...) -> object(Point(100,0), "red")),
           ],
           pathname=p"test/circle2.gif"
       )
"test\\circle2.gif"
```

**Comment by Wikunia** [comment]
I have seen that there is a bugfix directly in the repo. Shall I close this @jordancluts ?

**Pull request closed without merging**
