### PR TITLE
Pluto support

### LINKED ISSUE #208: Pluto Support and Integration
**Is your feature request related to a problem? Please explain.**

Currently, Javis does not work within a Pluto environment. One cannot use Javis to view frames of an animation easily like they could using the built-in Javis image viewer. Furthermore, on some platforms, the Javis image viewer is not performant due to it being built using Gtk.jl. 

We could perhaps get around this performance issue as well by providing browser-based support built around using Pluto as a platform.

**Describe the solution you'd like**

I would love to build functionality into Javis Pluto notebook support by creating something like this:

sliderplot

> Source: https://blog.dominodatalab.com/interactive-dashboards-in-jupyter/

But using Pluto instead. I think this functionality could be achieved by using [PlutoUi.jl](https://github.com/fonsp/PlutoUI.jl). Furthermore, this might be better suited to go into its own repository. So, initial development may take place on the main branch but later move to its own dedicated location. 

**Describe alternatives you've considered**

The best alternative would be the Javis image viewer but since not all platforms best support GTK based GUIs, this would provide greater applicability of Javis. I am not certain how Pluto will take to what I am imagining being an image viewer; I imagine Jupyter may be more performant but I am not sure at this point. Only experimentation will tell!

### PR DESCRIPTION
**Pull request by Sov-trotter**
## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [x] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [x] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [x] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [x] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [x] Did I properly add test dependencies to the `test` directory (if applicable)?
- [x] Did I check relevant tutorials that may be affected by changes in this PR?
- [x] Did I clearly articulate why this PR was made the way it was and how it was made?

**Link to relevant issue(s)**
Closes #208 

**How did you address these issues with this PR? What methods did you use?**
For the interactive feature, I have used a `_pluto_viewer` method which computes and stores the frames in-memory. Another alternative was using the internal methods in Javis as specified [here](https://github.com/Wikunia/Javis.jl/issues/208#issuecomment-807181579). But that isn't very user friendly.

When `liveviewer = false` I have created a small wrapper and an overload over the `Base.show` method to fetch and view the rendered gif.

### CODE REVIEW

**Comment by Wikunia** [comment]
Thanks @Sov-trotter 
I'm a bit confused this includes #288 , right? Would love to merge that one first. Is that okay?

**Comment by Sov-trotter** [comment]
Yeah!

**Comment by TheCedarPrince** [comment]
Hey @Sov-trotter - I finished reviewing your PR for Pluto. I cannot seem to get the slider to show up. Here is my notebook file:

```julia
### A Pluto.jl notebook ###
# v0.14.2

using Markdown
using InteractiveUtils

# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    quote
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : missing
        el
    end
end

# ╔═╡ 78269506-c35d-4613-97e8-c4968ad03e16
using PlutoUI

# ╔═╡ adf80b4c-befe-4f6d-b411-a1350a4c391b
using Javis

# ╔═╡ e882ff6f-d24f-4757-b52b-9c732491c0e4
function ground(args...)
    background("white") # canvas background
    sethue("black") # pen color
end

# ╔═╡ af3705d3-e0a4-4b29-9c45-35c8cba9362d
function object(p=O, color="black")
    sethue(color)
    circle(p, 25, :fill)
    return p
end

# ╔═╡ 6fedb208-b82f-4ee0-ab78-c31b28278545
function path!(points, pos, color)
    sethue(color)
    push!(points, pos) # add pos to points
    circle.(points, 2, :fill) # draws a circle for each point using broadcasting
end

# ╔═╡ a76ae8a0-bdce-4006-9012-35e7667f1d9f
function connector(p1, p2, color)
    sethue(color)
    line(p1,p2, :stroke)
end

# ╔═╡ ad9fa5e7-35bd-4861-a361-61e061923249
begin
	myvideo = Video(500, 500)

	path_of_red = Point[]
	path_of_blue = Point[]

	Background(1:70, ground)
	red_ball = Object(1:70, (args...)->object(O, "red"), Point(100,0))
	act!(red_ball, Action(anim_rotate_around(2π, O)))
	blue_ball = Object(1:70, (args...)->object(O, "blue"), Point(200,80))
	act!(blue_ball, Action(anim_rotate_around(2π, 0.0, red_ball)))
	Object(1:70, (args...)->connector(pos(red_ball), pos(blue_ball), "black"))
	Object(1:70, (args...)->path!(path_of_red, pos(red_ball), "red"))
	Object(1:70, (args...)->path!(path_of_blue, pos(blue_ball), "blue"))

	mygif = render(myvideo; liveview = true)

	@bind x Slider(1:1:70)

	mygif[x]	

end

# ╔═╡ Cell order:
# ╠═78269506-c35d-4613-97e8-c4968ad03e16
# ╠═adf80b4c-befe-4f6d-b411-a1350a4c391b
# ╠═e882ff6f-d24f-4757-b52b-9c732491c0e4
# ╠═af3705d3-e0a4-4b29-9c45-35c8cba9362d
# ╠═6fedb208-b82f-4ee0-ab78-c31b28278545
# ╠═a76ae8a0-bdce-4006-9012-35e7667f1d9f
# ╠═ad9fa5e7-35bd-4861-a361-61e061923249
```

Anything I am missing?

**Comment by Sov-trotter** [comment]
Thanks for looking in it. 
I'd suggest you take the render function and the slider out of the begin end block.
And put them in two different cells.

**Comment by TheCedarPrince** [comment]
Ah perfect @Sov-trotter - I think the only thing I have to suggest would be in the documentation workflow area, could you add some explanation on the requirement of putting `@bind` and `anim[x]` in different cells for the slider to show up? After that, I think this PR is good to go!

**Comment by Sov-trotter** [comment]
I am trying to understand this in the above code
```
# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    quote
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : missing
        el
    end
end
```
Could you share where would this notebook run outside of Pluto. Since internally `@bind` is only useful if `PlutoRunner` is defined. https://github.com/Wikunia/Javis.jl/pull/324/files#diff-763ffddd0fe1ffb533564007035f5947812905676655f155ce1ee4357eb53c5eR205

**Comment by Wikunia** [comment]
Sorry for the long wait @Sov-trotter 
I think that looks fantastic. Kind of the first time I enjoyed using Pluto :smile: 
Two things I would like to check before we merge this:
Do you mind providing a julia file that can simply be opened as an example in Pluto? Similar to the one provided by @TheCedarPrince  above but with the last two things in different cells. And then link to that example from the workflow inside the documentation.
The other point is: I don't have any experience with Pluto so maybe you can check this out.
When I added 
```
using LaTeXStrings
```
and later
```
Object(1:70, (args...)->latex(L"x^2"))
```
I got an error that `latex` is undefined. Is that an issue for you as well? For me it seems like it's a Pluto issue somewhere. If you can reproduce that and maybe @TheCedarPrince as well, we can open an issue there and make make a remark in the workflow section to prevent other people from getting that issue and being confused :smile:

**Comment by Sov-trotter** [comment]
Sure @Wikunia. The LaTeX declaration worked for me
image

**Comment by Wikunia** [comment]
LGTM. Make sure to resolve the changelog. Anything else from your side @TheCedarPrince ?

**Comment by Sov-trotter** [comment]
This is weird. Formatter returns true at my end but the test fails. :(

**Comment by Wikunia** [comment]
See: https://github.com/Sov-trotter/Javis.jl/pull/16 @Sov-trotter

**Comment by TheCedarPrince** [comment]
I made some changes here @Wikunia and @Sov-trotter to clarify and clean up the formatting. Otherwise, this has my full hearted approval! Merge when ready @Wikunia @Sov-trotter !

**Pull request merged**
