### PR TITLE
return nothing if pathname is empty and empty the constants

### PR DESCRIPTION
**Pull request by Wikunia**
## PR Checklist

The `CURRENT` constants should always be reset even if the liveviewer is used without a pathname. 
This fixes one point mentioned by @gpucce in #434 

**How did you address these issues with this PR? What methods did you use?**
I return `nothing` in that case and call `empty_CURRENT_constants`

### CODE REVIEW

**Review by gpucce — APPROVED** [review]

**Review by gpucce — APPROVED** [review]

**Comment by Wikunia** [comment]
Hmm I see. I think it's more a testing bug though but will have a look later. I think we shouldn't call `render` and assume to have access to the stuff later on. That is kind of what emptying the constants should make sure in the first place.

**Comment by gpucce** [comment]
> Hmm I see. I think it's more a testing bug though but will have a look later. I think we shouldn't call `render` and assume to have access to the stuff later on. That is kind of what emptying the constants should make sure in the first place.

yeah I think I get it, it happens because in the testing there are calls to functions involving `vid` after it has already been rendered right?

**Comment by Wikunia** [comment]
We should also empty those when we call the liveviewer which is done at the top of the `render` function.

**Review by gpucce — DISMISSED** [review]
Did not mean to ask my own review

**Comment by Wikunia** [comment]
Haha you approved it three times now and it is still buggy :smile:

**Comment by gpucce** [comment]
> Haha you approved it three times now and it is still buggy 😄

I don't know how this works, I wanted to make it un-approved but apperently that is not how it works? (sorry for the mess)

**Comment by Wikunia** [comment]
@TheCedarPrince I'm not super sure how the liveviewer works. Is there any possibility to clear the constants after the gtk window was closed?

**Review by gpucce — APPROVED** [review]

**Pull request merged**
