### PR TITLE
add central_limit_theorem

### PR DESCRIPTION
**Pull request by gpucce**
## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [ ] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [x] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [x] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [ ] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [ ] Did I properly add test dependencies to the `test` directory (if applicable)?
- [ ] Did I check relevant tutorials that may be affected by changes in this PR?
- [ ] Did I clearly articulate why this PR was made the way it was and how it was made?

I try to add the central_limit_theorem example. To do so I added central_limit_theorem.jl to the examples folder. central_limit_theorem.gif to the docs/src/assets/ folder and adited docs/src/examples.md to make the new one appear in a similar way to how the others do.

### CODE REVIEW

**Comment by gpucce** [comment]
Hi, I was wandering if there is something else I have to do for the pr because I don't understand some of the messages like those from codecov[bot]. Anyway if there is please tell me and I am happy to do it!

**Comment by Wikunia** [comment]
I don't know why it didn't run. Sorry I was quite busy over the weekend. Ping @TheCedarPrince if u have time to check this and merge

**Review by Wikunia — APPROVED** [review]
LGTM.
Any changes needed from your side @thecedarprince?

**Comment by TheCedarPrince** [comment]
image

**Comment by TheCedarPrince** [comment]
Thanks for the contribution @gpucce ! Looks really great and a very nice animation! :smile:

**Pull request merged**
