### PR TITLE
Add Require stuff

### LINKED ISSUE #193: Conditional Loading of Packages
**Is your feature request related to a problem? Please explain.**

I have noticed recently that `using Javis` seems to be taking much longer than it used to. I ran some benchmarks and it was somewhat concerning:

**v0.1.5 Benchmarks:**

```julia
julia> @time using Javis
 41.913861 seconds (37.30 M allocations: 2.000 GiB, 3.49% gc time)
```

**v0.1.0 Benchmarks:**

```julia
julia> @time using Javis
[ Info: Precompiling Javis [78b212ba-a7f9-42d4-b726-60726080707e]
 21.673696 seconds (12.55 M allocations: 715.007 MiB, 0.83% gc time)
```

We have currently doubled the compile time of `Javis`! :scream: 

**Describe the solution you'd like**

I would like to conditionally compile packages as they are needed. Obviously, some packages that are critical would always be loaded but I think we need to identify where the compile time issues come from.

**Describe alternatives you've considered**

Thanks to a suggestion from @mcabbott I think [`Requires.jl`](https://github.com/JuliaPackaging/Requires.jl) would help fix this problem.

### PR DESCRIPTION
**Pull request by Sov-trotter**
## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [ ] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [x] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [ ] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [x] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [ ] Did I properly add test dependencies to the `test` directory (if applicable)?
- [ ] Did I check relevant tutorials that may be affected by changes in this PR?
- [x] Did I clearly articulate why this PR was made the way it was and how it was made?

**Link to relevant issue(s)**
Closes #193 

**How did you address these issues with this PR? What methods did you use?**
Used the @requires method to load the javis_viewer.jl file since that's what uses Gtk
```
function __init__()
    @require Gtk="4c0ca9eb-093a-5379-98c5-f87ac0bbbf44" include("javis_viewer.jl")
end

```
Not sure if this is 100% correct but would be nice point to start from. I'd appreciate if someone could checkout this branch and provide feeback. :)

### CODE REVIEW

**Comment by Wikunia** [comment]
Currently only on mobile. Does this work locally on a test script? Seems like it's failing in CI as the file doesn't get included properly. 
I'm still puzzler of how this should work 🤣 How should Julia know that it has to include the file when we call the javis viewer?

**Comment by Sov-trotter** [comment]
Oh yeah. I am digging in a bit more. Just wanted the changes to be visible to everyone so that we know if it' the right direction.

**Comment by Wikunia** [comment]
Thanks for having a look 😊 Maybe it's as simple as having `using Gtk` inside the `if` in which we call the image viewer?

**Comment by Sov-trotter** [comment]
Okay. But we can extend it as:
-  The javis_viewer.jl has the code solely for the image viewer that can be made conditional based on whether Gtk is loaded or not. So I am trying something in towards that. 

Like you said this feature will be more beneficial for developers, Gtk.jl will be already precompiled in the first install of Javis, whereas it's the image viewer code that will be compiled everytime.

**Comment by Sov-trotter** [comment]
@TheCedarPrince what do you think?

**Comment by TheCedarPrince** [comment]
So after looking some more at Requires.jl, I am not sure if it actually does what I was expecting it to. I continue getting this error whenever I attempt to use liveview with an example. Here is my code:

```julia
   using Javis
   using LaTeXStrings

   function latex_ground(args...)
        translate(-200, -100)
        background("white")
        sethue("black")
        fontsize(50)
    end 
    
    video = Video(400, 200)
    javis(
        video,
        [
            BackgroundAction(1:1, latex_ground),
            Action((args...) -> latex(L"\mathcal{O}(\log{n})")), # default fontsize 50
            BackgroundAction(1:35, latex_ground),
            Action(
                (args...) -> latex(L"\mathcal{O}(\log{n})");
                subactions = [ 
                    SubAction(1:15, appear(:draw_text)),
                    SubAction(21:35, disappear(:draw_text)),
                ],
            ), # default fontsize 50
        ],
        pathname = "latex.gif",
        liveview = true
    )   
```

and here is the error

```julia
julia> include("view.jl")
[ Info: Precompiling Javis [78b212ba-a7f9-42d4-b726-60726080707e]
ERROR: LoadError: UndefVarError: _javis_viewer not defined
Stacktrace:
 [1] javis(::Video, ::Array{Action,1}; framerate::Int64, pathname::String, liveview::Bool, tempdirectory::String) at /home/src/Projects/javis/src/Javis.jl:217
 [2] top-level scope at /home/src/Projects/javis/view.jl:12
 [3] include(::String) at ./client.jl:457
 [4] top-level scope at REPL[2]:1
in expression starting at /home/src/Projects/javis/view.jl:12
```

@Sov-trotter , you are free to continue exploring Requires.jl but @Wikunia 's simple solution of a conditional may be the best case here. I was hoping for something more elegant which is why I was attracted to Requires.jl. 

Let me know if you have any more questions!

**Comment by Sov-trotter** [comment]
Okay. Now I see. Require will be helpful where things are not as convoluted/inter-dependent like here in Javis. I also tried some benchmarks and using Javis took around 25s for me. Closing this for now.  :)

**Comment by Sov-trotter** [comment]
I was digging around a bit more and came across https://github.com/JuliaReinforcementLearning/GridWorlds.jl/commit/f46e78c3ff224039adb42a3362edee5c8a053428

**Comment by Sov-trotter** [comment]
Not sure if it's possible but just putting it down here.
@Wikunia do you think we can solve this by creating a `Task` at the global level which imports `Gtk` and schedule it conditionally on the basis of `liveviewer` flag?
https://docs.julialang.org/en/v1/base/parallel/

**Comment by Wikunia** [comment]
I think we should try this again with v1.6 of Julia and decide whether it's really necessary. Additionally it might make more sense to split up the package into some parts.

**Pull request closed without merging**
